version: '3.8'

services:
  app:
    build:
      context: ./docker/prod/php
      dockerfile: Dockerfile
    container_name: api_app_php
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
      - lab

  nginx:
    build:
      context: ./docker/prod/nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    restart: always
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    ports:
      - '${DB_PORT_DOCKER:-3336}:3306'
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  lab:
    external: true

volumes:
  mysql:
