version: '3.8'

services:
  app:
    build:
      context: ./docker/prod/php
      dockerfile: Dockerfile
    container_name: api_app_php
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  nginx:
    build:
      context: ./docker/prod/nginx
      dockerfile: Dockerfile
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - './docker/mysql:/var/lib/mysql'
    ports:
      - "3306:3306"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  docker/mysql:
